BLOCK_SIZE = 100
DATABASE_PATH = "static/Hands"
DORSAL_DATABASE_PATH = "store/dorsalImages"
PALMAR_DATABASE_PATH = "store/palmarImages"
IMAGE_IDS_CSV = "store/imageIds.csv"
DORSAL_IMAGE_IDS_CSV = "store/dorsal_imageIds.csv"
PALMAR_IMAGE_IDS_CSV = "store/palmar_imageIds.csv"
DISTANCES_PAIR_WISE_STORE = "store/distances"
FEATURE_STORE = "store/features"
DISTANCES_MATRIX_STORE = "store/distances/matrix"
DORSAL_DISTANCES_MATRIX_STORE = "store/distances/dorsal"
PALMAR_DISTANCES_MATRIX_STORE = "store/distances/palmar"
GRAPH_STORE="store/graphs"
DORSAL_GRAPH_STORE="store/graphs/dorsal"
PALMAR_GRAPH_STORE="store/graphs/palmar"

CLASSIFICATION_IMG_DIR = "/Users/yvtheja/Documents/Dataset2"
CLASSIFICATION_META_CSV = "/Users/yvtheja/Documents/labelled_set1.csv"
